### ISSUE TITLE
Build error when using Musl SDK

### ISSUE THREAD

**Issue by Cyberbeni** [swiftlang/swift-build#1573]
Linux Mint 22.3, Swift 6.3.3
Project: https://codeberg.org/Cyberbeni/auth.home.arpa
Commit: dd1d39311bc8d964195c9456acbd2223b618cb6d
Run `swift package update` to resolve https://github.com/swiftlang/swift-build/issues/1512
Run `swift build --build-system swiftbuild --swift-sdk x86_64-swift-linux-musl` to observe the build error
When using the regular Linux SDK or the other build system, it compiles without error.

First error:
```console
/home/cyberbeni/Developer/auth.home.arpa/.build/checkouts/swift-crypto/Sources/Crypto/AEADs/AES/GCM/AES-GCM.swift:15:19: error: no such module 'CryptoKit'
@_exported import CryptoKit
                  ^
```

**Comment by finagolfin** [comment]
Still seeing this with the latest 6.4 or trunk snapshots? There have been platform-filtering issues in the past, could be one of them.

If you're only trying swift-build with 6.3, a lot has changed since then.
