### PR TITLE
Centralize dependency diagnostics in `ValidateDependencies` action

### PR DESCRIPTION
**Pull request by neonichu**
Instead of emitting diagnostics directly, individual tasks emit .dependencies files which are read by a per-target action which aggregates them. This avoids duplication of diagnostics across tasks.

rdar://156174696

### CODE REVIEW

**Comment by neonichu** [comment]
@swift-ci please test

File: Sources/SWBTaskExecution/TaskActions/ClangCompileTaskAction.swift [hunk 1]
```diff
@@ -335,13 +338,15 @@ public final class ClangCompileTaskAction: TaskAction, BuildValueValidatingTaskA
...
-                if diagnostics.contains(where: { $0.behavior == .error }) {
-                    return .failed
+                if let dependencyValidationOutputPath {
+                    let validationInfo = DependencyValidationInfo(files: files)
+                    _ = try executionDelegate.fs.writeIfChanged(
+                        dependencyValidationOutputPath,
+                        contents: ByteString(
+                            JSONEncoder(outputFormatting: .sortedKeys).encode(validationInfo)
+                        )
+                    )
```
Comment (neonichu) [inline Sources/SWBTaskExecution/TaskActions/ClangCompileTaskAction.swift:349]: I'm a bit ambivalent on whether the validation action should just be directly consuming the trace files. It seems right for the Clang action to know about the implementation details here, but on the other hand it does seem a tiny bit wasteful to just process these files into other files?

File: Tests/SWBBuildSystemTests/DependencyValidationTests.swift [hunk 2]
```diff
@@ -493,7 +494,7 @@ fileprivate struct DependencyValidationTests: CoreBasedTests {
                             TestStandardTarget(
                                 "CoreFoo", type: .framework,
                                 buildPhases: [
-                                    TestSourcesBuildPhase(["CoreFoo.m"]),
+                                    TestSourcesBuildPhase(["CoreFoo.m", "CoreBar.m"]),
```
Comment (neonichu) [inline Tests/SWBBuildSystemTests/DependencyValidationTests.swift:497]: This makes it so that the test would see duplicate diagnostics in the old implementation which this PR then fixes.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
Linux jobs are failing with

```
Unable to find error: '.contains("Missing entries in MODULE_DEPENDENCIES: Foundation")' (other errors: ["Unexpected error in querying jobs from dependency graph: The operation could not be completed. The file doesn’t exist. (for task: [\"SwiftDriver\", \"TargetB\", \"normal\", \"x86_64\", \"com.apple.xcode.tools.swift.compiler\"])"])
```

**Comment by neonichu** [comment]
Also same issue on Windows (TIL on Windows, the testing output uses `×` instead of `✘`).

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
From the cmake job:

`TaskGeneration.swift:192:35: error: cannot find type 'ValidateDependenciesSpec' in scope`

I guess I need to update the configs for that.

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
@swift-ci please test

**Comment by neonichu** [comment]
The failures on focal are expected and we're dropping the jobs in #676

File: Sources/SWBCore/Dependencies.swift [hunk 3]
```diff
@@ -235,3 +235,34 @@ public struct ModuleDependenciesContext: Sendable, SerializableCodable {
...
+
+    public enum Payload: Hashable, Sendable, Codable {
+        case clangDependencies(files: [String])
+        case swiftDependencies(imports: [Import])
+        case unsupported
+    }
+
+    public let payload: Payload
+
+    public init(files: [Path]?) {
```
Comment (mirza-garibovic) [inline Sources/SWBCore/Dependencies.swift]: I think a single `init` that accepts `Payload` is easier to maintain, that way you don't have to change or add new inits when you change `Payload`

File: Sources/SWBCore/SpecImplementations/Tools/ValidateDependencies.swift [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+    public func createTasks(_ cbc: CommandBuildContext, _ delegate: any TaskGenerationDelegate, dependencyInfos: [PlannedPathNode], payload: ValidateDependenciesPayload) async {
+        guard let configuredTarget = cbc.producer.configuredTarget else {
+            return
+        }
+        let output =  delegate.createVirtualNode("ValidateDependencies \(configuredTarget.guid)")
+        delegate.createTask(type: self, payload: payload, ruleInfo: ["ValidateDependencies"], commandLine: ["builtin-validate-dependencies"] + dependencyInfos.map { $0.path.str }, environment: EnvironmentBindings(), workingDirectory: cbc.producer.defaultWorkingDirectory, inputs: dependencyInfos + cbc.commandOrderingInputs, outputs: [output], action: delegate.taskActionCreationDelegate.createValidateDependenciesTaskAction(), preparesForIndexing: false, enableSandboxing: false)
+    }
+}
+
+public struct ValidateDependenciesPayload: TaskPayload, Sendable {
```
Comment (mirza-garibovic) [inline Sources/SWBCore/SpecImplementations/Tools/ValidateDependencies.swift]: I'd make this `CodableSerializable`, there's only one per target, it's fast enough

File: Sources/SWBTaskExecution/TaskActions/ValidateDependenciesTaskAction.swift [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+            var diagnostics: [Diagnostic] = []
+
+            if unsupported {
+                diagnostics.append(contentsOf: context.makeDiagnostics(files: nil))
+            } else {
+                diagnostics.append(contentsOf: context.makeDiagnostics(files: allFiles.map { Path($0) }))
+                diagnostics.append(contentsOf: context.makeDiagnostics(imports: allImports.map { ($0.dependency, $0.importLocations) }))
+            }
+
+            for diagnostic in diagnostics {
```
Comment (mirza-garibovic) [inline Sources/SWBTaskExecution/TaskActions/ValidateDependenciesTaskAction.swift:70]: I think this is still going to create duplicates if both clang and swift sources in the same target have the same module deps.

Comment (mirza-garibovic) [reply Sources/SWBTaskExecution/TaskActions/ValidateDependenciesTaskAction.swift:70]: Maybe it's time to merge the Swift and Clang tests as part of this?

File: Sources/SWBTaskExecution/TaskActions/ClangCompileTaskAction.swift (hunk 1 above)
Comment (mirza-garibovic) [reply Sources/SWBTaskExecution/TaskActions/ClangCompileTaskAction.swift:349]: This seems like a good place to start! Easy to change later.

File: Sources/SWBCore/SpecImplementations/Tools/SwiftCompiler.swift [hunk 6]
```diff
@@ -273,6 +273,29 @@ public struct SwiftSourceFileIndexingInfo: SourceFileIndexingInfo {
     }
 }
 
+public struct SwiftDependencyValidationPayload: Serializable, Encodable, Sendable {
```
Comment (mirza-garibovic) [inline Sources/SWBCore/SpecImplementations/Tools/SwiftCompiler.swift]: Also `CodableSerializable` here

File: Sources/SWBTaskExecution/TaskActions/ValidateDependenciesTaskAction.swift (hunk 5 above)
Comment (neonichu) [reply Sources/SWBTaskExecution/TaskActions/ValidateDependenciesTaskAction.swift:70]: Good point. 

I think I'll make that a separate PR since this one is already a sizable change and self-contained.

**Comment by neonichu** [comment]
@swift-ci please test

**Review by mirza-garibovic — APPROVED** [review]

File: Sources/SWBTaskExecution/TaskActions/ValidateDependenciesTaskAction.swift (hunk 5 above)
Comment (neonichu) [reply Sources/SWBTaskExecution/TaskActions/ValidateDependenciesTaskAction.swift:70]: #696 is the follow-up for avoiding cross-language duplication
